CREATE DATABASE ProyectoTiendaZapatos
GO

USE ProyectoTiendaZapatos
GO

ALTER AUTHORIZATION ON DATABASE::ProyectoTiendaZapatos TO sa
GO
	-- Tablas

CREATE TABLE rol (
	id INT IDENTITY ( 1 , 1 ) PRIMARY KEY,
	nombre VARCHAR (20) NOT NULL,
	estado BIT NOT NULL DEFAULT 1
);
GO

CREATE TABLE usuario (
	id INT IDENTITY ( 1 , 1 ) PRIMARY KEY,
	usuario VARCHAR (50) NOT NULL UNIQUE,
	contrasenia VARCHAR (100) NOT NULL,
	id_Rol INT NOT NULL FOREIGN KEY REFERENCES rol (id) ON UPDATE CASCADE,
	estado BIT NOT NULL DEFAULT 1
);
GO

CREATE TABLE tipoDocumento (
	id INT IDENTITY (1,1) PRIMARY KEY,
	nombre VARCHAR (50) NOT NULL,
	estado BIT NOT NULL DEFAULT 1
);
GO

CREATE TABLE iva (
	id INT IDENTITY (1,1) PRIMARY KEY,
	iva VARCHAR (5) NOT NULL ,
	estado BIT NOT NULL DEFAULT 1
);
GO

CREATE TABLE categoria (
	id INT IDENTITY (1,1) PRIMARY KEY,
	nombre VARCHAR (5) NOT NULL,
	descripcion VARCHAR (100),
	descuento INT NOT NULL,
	estado BIT NOT NULL DEFAULT 1
);
GO

CREATE TABLE tipoCliente (
	id INT IDENTITY (1,1) PRIMARY KEY,
	nombre VARCHAR (50) NOT NULL,
	estado BIT NOT NULL DEFAULT 1
);
GO

CREATE TABLE departamento (
	id INT IDENTITY (1,1) PRIMARY KEY,
	nombre VARCHAR (100) NOT NULL,
	estado BIT NOT NULL DEFAULT 1
);
GO

CREATE TABLE municipio (
	id INT IDENTITY (1,1) PRIMARY KEY,
	nombre VARCHAR (100) NOT NULL,
	id_Departamento INT NOT NULL FOREIGN KEY REFERENCES departamento (id) ON DELETE NO ACTION ON UPDATE CASCADE,
	estado BIT NOT NULL DEFAULT 1
);
GO

CREATE TABLE color (
	id INT IDENTITY (1,1) PRIMARY KEY,
	nombre VARCHAR (100) NOT NULL,
	estado BIT NOT NULL DEFAULT 1
);
GO

CREATE TABLE tallas (
	id INT IDENTITY (1,1) PRIMARY KEY,
	talla VARCHAR (2) NOT NULL,
	estado BIT NOT NULL DEFAULT 1
);
GO

CREATE TABLE coleccion (
	id INT IDENTITY (1,1) PRIMARY KEY,
	nombre VARCHAR (100) NOT NULL,
	epoca VARCHAR (50) NOT NULL,
	estado BIT NOT NULL DEFAULT 1
);
GO

CREATE TABLE material (
	id INT IDENTITY (1,1) PRIMARY KEY,
	nombre VARCHAR (100) NOT NULL,
	estado BIT NOT NULL DEFAULT 1
);
GO

CREATE TABLE tipoCalzado (
	id INT IDENTITY (1,1) PRIMARY KEY,
	nombre VARCHAR (100) NOT NULL,
	estado BIT NOT NULL DEFAULT 1
);
GO

CREATE TABLE tipoPago (
	id INT IDENTITY (1,1) PRIMARY KEY,
	nombre VARCHAR (100) NOT NULL,
	estado BIT NOT NULL DEFAULT 1
);
GO

CREATE TABLE cliente (
	numID VARCHAR (20) PRIMARY KEY,
	id_TipoDocumento INT NOT NULL FOREIGN KEY REFERENCES tipoDocumento (id) ON DELETE NO ACTION ON UPDATE CASCADE,
	nombres VARCHAR (100) NOT NULL,
	apellidos VARCHAR (100) NOT NULL,
	fchNac DATE NOT NULL,
	direccion VARCHAR (100) NOT NULL,
	telefono VARCHAR (10) NOT NULL,
	correoElectronico VARCHAR (100) UNIQUE NOT NULL,
	contrasenia VARCHAR (100) NOT NULL,
	id_TipoCliente INT NOT NULL FOREIGN KEY REFERENCES tipoCliente (id) ON DELETE NO ACTION ON UPDATE CASCADE,
	id_Municipio INT NOT NULL FOREIGN KEY REFERENCES municipio (id) ON DELETE NO ACTION ON UPDATE CASCADE,
	id_Categoria INT NOT NULL FOREIGN KEY REFERENCES categoria (id) ON DELETE NO ACTION ON UPDATE CASCADE,
	estado BIT NOT NULL DEFAULT 1
);
GO

CREATE TABLE empresa (
	numID_Cliente VARCHAR (20) NOT NULL FOREIGN KEY REFERENCES cliente (numID) ON DELETE NO ACTION ON UPDATE CASCADE UNIQUE,
	NIT VARCHAR (20) NOT NULL UNIQUE,
	PRIMARY KEY (numID_Cliente, NIT),
	nombreEmpresa VARCHAR (100) NOT NULL,
	dirBodega VARCHAR (100) NOT NULL,
	estado BIT NOT NULL DEFAULT 1
);
GO

CREATE TABLE producto (
	id INT IDENTITY (1,1) PRIMARY KEY,
	nombreProd VARCHAR (100) NOT NULL,
	id_Color INT NOT NULL FOREIGN KEY REFERENCES color (id) ON DELETE NO ACTION ON UPDATE CASCADE,
	id_Coleccion INT NOT NULL FOREIGN KEY REFERENCES coleccion (id) ON DELETE NO ACTION ON UPDATE CASCADE,
	id_Material INT NOT NULL FOREIGN KEY REFERENCES material (id) ON DELETE NO ACTION ON UPDATE CASCADE,
	id_TipoCAlzado INT NOT NULL FOREIGN KEY REFERENCES tipoCalzado (id) ON DELETE NO ACTION ON UPDATE CASCADE,
	estado BIT NOT NULL DEFAULT 1
);
GO

CREATE TABLE producto_talla (
	id INT IDENTITY (1,1) PRIMARY KEY,
	id_Producto INT NOT NULL FOREIGN KEY REFERENCES producto (id) ON DELETE NO ACTION ON UPDATE CASCADE,
	id_Talla INT NOT NULL FOREIGN KEY REFERENCES tallas (id) ON DELETE NO ACTION ON UPDATE CASCADE,	
	valUnitario INT NOT NULL,
	cant SMALLINT NOT NULL,
	estado BIT NOT NULL DEFAULT 1
);
GO

CREATE TABLE pedido (
	id INT IDENTITY (1,1) PRIMARY KEY,
	id_Producto_talla INT NOT NULL FOREIGN KEY REFERENCES producto_talla (id) ON DELETE NO ACTION ON UPDATE CASCADE UNIQUE,
	cant SMALLINT NOT NULL,
	estado BIT NOT NULL DEFAULT 1
);
GO

CREATE TABLE detallesFactura (
	id INT IDENTITY (1,1) PRIMARY KEY,
	id_Pedido INT NOT NULL FOREIGN KEY REFERENCES pedido (id) ON DELETE NO ACTION ON UPDATE CASCADE,
	descripcion VARCHAR (100),
	id_TipoPago INT NOT NULL FOREIGN KEY REFERENCES tipoPago (id) ON DELETE NO ACTION ON UPDATE CASCADE,
	id_Iva INT NOT NULL FOREIGN KEY REFERENCES iva (id) ON DELETE NO ACTION ON UPDATE CASCADE,
	subtotal INT NOT NULL,
	total INT NOT NULL
);
GO

CREATE TABLE factura (
	id INT IDENTITY (1,1) PRIMARY KEY,
	fchExpedicion DATETIME NOT NULL,
	id_Cliente VARCHAR (20) NOT NULL FOREIGN KEY REFERENCES cliente (numID) ON DELETE NO ACTION ON UPDATE CASCADE ,
	id_DetallesFactura INT NOT NULL FOREIGN KEY REFERENCES detallesFactura (id)  ON DELETE NO ACTION ON UPDATE CASCADE UNIQUE,
	id_Municipio INT NOT NULL FOREIGN KEY REFERENCES municipio (id)
);
GO



CREATE PROCEDURE LOL
    @CONSULTA NVARCHAR(MAX),
    @CONDICION NVARCHAR(MAX)
AS
BEGIN
    DECLARE @sql NVARCHAR(MAX)

    -- Construir la consulta SQL completa
    SET @sql = N'SELECT ' + QUOTENAME(@CONSULTA) + ' FROM usuario WHERE ' + @CONDICION

    -- Ejecutar la consulta
    EXEC sp_executesql @sql
END
